import { globalIgnores } from "eslint/config";
import { base } from "@arena/eslint-config/base";

const config = [
  ...base,
  // Generated by drizzle-kit.
  globalIgnores(["drizzle/**"]),
  {
    // Run by pnpm directly (drizzle-kit, the backfills), never by Turborepo:
    // turbo.json's env doesn't apply to them.
    files: ["drizzle.config.ts", "scripts/**"],
    rules: { "turbo/no-undeclared-env-vars": "off" },
  },
];

export default config;
